<?php
/**
 * BitbucketSyncTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Phrase
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Phrase;

use PHPUnit\Framework\TestCase;

/**
 * BitbucketSyncTest Class Doc Comment
 *
 * @category    Class
 * @description BitbucketSync
 * @package     Phrase
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BitbucketSyncTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BitbucketSync"
     */
    public function testBitbucketSync()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "repository_name"
     */
    public function testPropertyRepositoryName()
    {
    }

    /**
     * Test attribute "last_export_to_bitbucket_at"
     */
    public function testPropertyLastExportToBitbucketAt()
    {
    }

    /**
     * Test attribute "last_import_from_bitbucket_at"
     */
    public function testPropertyLastImportFromBitbucketAt()
    {
    }

    /**
     * Test attribute "valid_phraseapp_yaml"
     */
    public function testPropertyValidPhraseappYaml()
    {
    }

    /**
     * Test attribute "phraseapp_projects"
     */
    public function testPropertyPhraseappProjects()
    {
    }
}
