<?php
/**
 * OrganizationJobTemplateCreateParametersTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Phrase
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Phrase;

use PHPUnit\Framework\TestCase;

/**
 * OrganizationJobTemplateCreateParametersTest Class Doc Comment
 *
 * @category    Class
 * @description OrganizationJobTemplateCreateParameters
 * @package     Phrase
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class OrganizationJobTemplateCreateParametersTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrganizationJobTemplateCreateParameters"
     */
    public function testOrganizationJobTemplateCreateParameters()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "briefing"
     */
    public function testPropertyBriefing()
    {
    }
}
