<?php
/**
 * ProjectCreateParametersTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Phrase
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Phrase;

use PHPUnit\Framework\TestCase;

/**
 * ProjectCreateParametersTest Class Doc Comment
 *
 * @category    Class
 * @description ProjectCreateParameters
 * @package     Phrase
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ProjectCreateParametersTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProjectCreateParameters"
     */
    public function testProjectCreateParameters()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "main_format"
     */
    public function testPropertyMainFormat()
    {
    }

    /**
     * Test attribute "media"
     */
    public function testPropertyMedia()
    {
    }

    /**
     * Test attribute "shares_translation_memory"
     */
    public function testPropertySharesTranslationMemory()
    {
    }

    /**
     * Test attribute "project_image"
     */
    public function testPropertyProjectImage()
    {
    }

    /**
     * Test attribute "remove_project_image"
     */
    public function testPropertyRemoveProjectImage()
    {
    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {
    }

    /**
     * Test attribute "point_of_contact"
     */
    public function testPropertyPointOfContact()
    {
    }

    /**
     * Test attribute "source_project_id"
     */
    public function testPropertySourceProjectId()
    {
    }

    /**
     * Test attribute "workflow"
     */
    public function testPropertyWorkflow()
    {
    }

    /**
     * Test attribute "machine_translation_enabled"
     */
    public function testPropertyMachineTranslationEnabled()
    {
    }

    /**
     * Test attribute "enable_branching"
     */
    public function testPropertyEnableBranching()
    {
    }

    /**
     * Test attribute "protect_master_branch"
     */
    public function testPropertyProtectMasterBranch()
    {
    }

    /**
     * Test attribute "enable_all_data_type_translation_keys_for_translators"
     */
    public function testPropertyEnableAllDataTypeTranslationKeysForTranslators()
    {
    }

    /**
     * Test attribute "enable_icu_message_format"
     */
    public function testPropertyEnableIcuMessageFormat()
    {
    }

    /**
     * Test attribute "zero_plural_form_enabled"
     */
    public function testPropertyZeroPluralFormEnabled()
    {
    }

    /**
     * Test attribute "autotranslate_enabled"
     */
    public function testPropertyAutotranslateEnabled()
    {
    }

    /**
     * Test attribute "autotranslate_check_new_translation_keys"
     */
    public function testPropertyAutotranslateCheckNewTranslationKeys()
    {
    }

    /**
     * Test attribute "autotranslate_check_new_uploads"
     */
    public function testPropertyAutotranslateCheckNewUploads()
    {
    }

    /**
     * Test attribute "autotranslate_check_new_locales"
     */
    public function testPropertyAutotranslateCheckNewLocales()
    {
    }

    /**
     * Test attribute "autotranslate_mark_as_unverified"
     */
    public function testPropertyAutotranslateMarkAsUnverified()
    {
    }

    /**
     * Test attribute "autotranslate_use_machine_translation"
     */
    public function testPropertyAutotranslateUseMachineTranslation()
    {
    }

    /**
     * Test attribute "autotranslate_use_translation_memory"
     */
    public function testPropertyAutotranslateUseTranslationMemory()
    {
    }

    /**
     * Test attribute "smart_suggest_enabled"
     */
    public function testPropertySmartSuggestEnabled()
    {
    }

    /**
     * Test attribute "smart_suggest_use_glossary"
     */
    public function testPropertySmartSuggestUseGlossary()
    {
    }

    /**
     * Test attribute "smart_suggest_use_machine_translation"
     */
    public function testPropertySmartSuggestUseMachineTranslation()
    {
    }
}
