<?php
/**
 * TranslationsVerifyParametersTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Phrase
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Phrase API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Phrase;

use PHPUnit\Framework\TestCase;

/**
 * TranslationsVerifyParametersTest Class Doc Comment
 *
 * @category    Class
 * @description TranslationsVerifyParameters
 * @package     Phrase
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TranslationsVerifyParametersTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TranslationsVerifyParameters"
     */
    public function testTranslationsVerifyParameters()
    {
    }

    /**
     * Test attribute "branch"
     */
    public function testPropertyBranch()
    {
    }

    /**
     * Test attribute "locale_id"
     */
    public function testPropertyLocaleId()
    {
    }

    /**
     * Test attribute "q"
     */
    public function testPropertyQ()
    {
    }
}
