<?php
/**
 * ProjectsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Phrase
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Phrase;

use \Phrase\Configuration;
use \Phrase\ApiException;
use \Phrase\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProjectsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Phrase
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProjectsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for projectCreate
     *
     * Create a project.
     *
     */
    public function testProjectCreate()
    {
    }

    /**
     * Test case for projectDelete
     *
     * Delete a project.
     *
     */
    public function testProjectDelete()
    {
    }

    /**
     * Test case for projectShow
     *
     * Get a single project.
     *
     */
    public function testProjectShow()
    {
    }

    /**
     * Test case for projectUpdate
     *
     * Update a project.
     *
     */
    public function testProjectUpdate()
    {
    }

    /**
     * Test case for projectsList
     *
     * List projects.
     *
     */
    public function testProjectsList()
    {
    }
}
